# Generated by Django 3.1.4 on 2020-12-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
